### ISSUE TITLE
missing helper_math.h

### ISSUE THREAD

**Issue by frischzenger** [ipeter50/ken-burns-effect#2]
when i run kbe.py, meet the following error
fatal error: /home/s182169/Master_thesis/GAN-Burns-Effect/utils/helper_math.h: no such file or directory

**Comment by pierlj** [comment]
Hi, I forgot to remove an hardcoded path. I just updated it. 
You can try again with the updated version. You can now change the path to the math helper in /utils/common.py l.14.
You must provide here the full path in your system to ./utils/helper_math.h. 

I will update the readme to explain that.
