### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 123yuyu** [ipeter50/ken-burns-effect#5]
Can you post the dataset, please? thank you

**Comment by pierlj** [comment]
For detph training I used NYUv2 and DIML dataset but you can now find larger depth datasets online. In particular the synthetic dataset that was used by the original paper [here](https://github.com/sniklaus/3d-ken-burns). 

For inpainting, I used the same dataset for which I simulated occlusion masks to mask some parts of the images. 

The details can be found in my Master thesis (link in the README).
