### ISSUE TITLE
one question about the cv2.cvtColor(numpyImage, cv2.COLOR_BGR2RGB)

### ISSUE THREAD

**Issue by ccsvd** [ipeter50/ken-burns-effect#7]
hi,@pierlj
i read the readme file and know use pretrained_estim=True to set  cv2.cvtColor(numpyImage, cv2.COLOR_BGR2RGB) when use the model from original paper,but i doubt:
1、the original code do not have to  use cv2.cvtColor(numpyImage, cv2.COLOR_BGR2RGB);
2、your train code use  cv2.cvtColor(numpyImage, cv2.COLOR_BGR2RGB) on data_loader.py,so when inference it should have to use it, but on your kbe.py code it is not;
thanks!

**Comment by pierlj** [comment]
Hi, 
There might be a mistake in the code indeed. `cvtColor` should be used when `pretrained_estim=False`. 

I cannot conduct any test to make sure that this does change the quality of the KBE. Try it out and make a PR, if it provides any improvements, I will push the modification.

**Comment by ccsvd** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
