### ISSUE TITLE
could you please tell me how to get the training dataset？

### ISSUE THREAD

**Issue by wududu123** [ipeter50/ken-burns-effect#9]
hi，
I want to train estimation。
I found 'path': '/scratch/s182169/GTAV_1080/',  in train.py.
do you have  a new dataset? 
Can you share it with me?

**Comment by pierlj** [comment]
Hi, 
This dataset is public, it can be downloaded [here](https://phuang17.github.io/DeepMVS/mvs-synth.html). 

Of course, once downloaded, you need to change the path in the code to match your setup.

**Comment by wududu123** [comment]
> Hi, This dataset is public, it can be downloaded [here](https://phuang17.github.io/DeepMVS/mvs-synth.html).
> 
> Of course, once downloaded, you need to change the path in the code to match your setup.

Thank you so much
